export const ADD='ADD'
export const REDUCE='REDUCE'
export const SET_MSG='SET_MSG'
export const SAVE_ARTICLE='SAVE_ARTICLE'
export const SAVE_ARTICLES_BY_CATALOGID='SAVE_ARTICLES_BY_CATALOGID'
export const GET_ARTICLES_BY_CATALOGID='GET_ARTICLES_BY_CATALOGID'

